### PR TITLE
fix typo in README

### PR DESCRIPTION
**Pull request by kmoe**

### CODE REVIEW

**Comment by ryanbrainard** [comment]
Sorry to be a pain, but the way GitHub is showing this diff with the soft wraps, I can't tell what changed. Can you add a quick PR description?

**Comment by kmoe** [comment]
Just a s/let's/lets in "instead of mapping state to props, this let's you map props to URLs to props" -> "instead of mapping state to props, this lets you map props to URLs to props"

**Comment by kmoe** [comment]
Ah, didn't noticed you'd merged a subsequent PR with this fix.

**Comment by ryanbrainard** [comment]
Thanks anyway! :)

**Pull request closed without merging**
