### PR TITLE
Upgrade "warning" and "hoist-non-react-statics"

### PR DESCRIPTION
**Pull request by ipanasenko**

### CODE REVIEW

**Comment by ryanbrainard** [comment]
Curious, what is the reason for upgrading these two? What issue is this fixing?

**Comment by ipanasenko** [comment]
@ryanbrainard nothing, just two outdated dependencies, which caused multiple versions of same packages in my project, that's it

**Comment by ryanbrainard** [comment]
Ok, I'll pull this in and put it out as a patch beta so folks and try it out

**Comment by ryanbrainard** [comment]
Released in https://github.com/heroku/react-refetch/releases/tag/v1.0.3-0

**Pull request merged**
