### PR TITLE
Add support for Request.mode

### PR DESCRIPTION
**Pull request by ryanbrainard**
This has been requested a few times, so adding support for [`Request.mode`](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode).

https://github.com/heroku/react-refetch/issues/154

### CODE REVIEW

**Comment by jsullivan** [comment]
This LGTM. I'm restarting Travis to see if those connection timeouts from the last build self-resolve.

**Comment by jsullivan** [comment]
Hm, not sure what's up with Travis.

**Comment by ryanbrainard** [comment]
@jsullivan turns out we were using a super ancient version of npm. I synced it up with what react-redux is using for versions.

**Comment by jsullivan** [comment]
LGTM! Bring it on in. :)

**Pull request merged**
