### PR TITLE
Readme - Update Manual Refetch Section

### PR DESCRIPTION
**Pull request by jwdotjs**
Update manual refetch section of readme to discuss the mapping comparison behavior that occurs when a refetch is triggered and how a developer can modify the default behavior if they wish to do so.

Refs https://github.com/heroku/react-refetch/issues/26

### CODE REVIEW

**Comment by hnordt** [comment]
I liked the additional explanation :+1:

**Comment by ryanbrainard** [comment]
Thanks for writing this up. Re-reading the example, I can see how it's easy it would be to misunderstand this. I'm also going to fix up the example and make a couple tweaks to make this clearer.

**Comment by ryanbrainard** [comment]
I may have gone a little overboard in my ["tweaking"](https://github.com/heroku/react-refetch/commit/3d52b32365f1325f7d1f03d473d54a726d811215) and ended up incorporating your additional into the example instead of making it stand alone. Please let me know if it still captures the spirt of what you wanted to convey.

**Comment by jwdotjs** [comment]
I think the new documentation perfectly demonstrates how manual refetching is expected to work right out of the box. :+1: 

Thanks again Ryan!

**Pull request merged**
