### PR TITLE
ignore then/catch mapping result if returned undefined

### PR DESCRIPTION
**Pull request by nfcampos**
this allows the use of `then` and `catch` for side effects. I chose to ignore the return value only if it is `undefined`, anything else will go through the same logic as before (eg. throwing if you return something other than a plain object, etc.)

partially addresses #58

remind me to update the docs before you merge this

### CODE REVIEW

**Comment by jsullivan** [comment]
LGTM. Want to update the docs before I merge?

**Comment by nfcampos** [comment]
@jsullivan I've updated the docs :)

**Comment by jsullivan** [comment]
@nfcampos I'm bringing this in, too. Mind merging or rebasing first?

**Comment by jsullivan** [comment]
Also, thanks for this and all of your other contributions :heart:.

**Comment by jsullivan** [comment]
@nfcampos n/m, I don't see any conflicts so I'm going ahead and bringing this in.

**Comment by nfcampos** [comment]
Thanks :)

**Comment by ryanbrainard** [comment]
@jsullivan thanks for handling this while I was out.
@nfcampos looks good! 👍

**Pull request merged**
